apiVersion: tracee.aquasec.com/v1beta1
kind: Policy
metadata:
  name: openclaw-security
  annotations:
    description: Runtime security policy for OpenClaw containers — enforcement enabled
spec:
  scope:
    - global
  rules:
    # === ENFORCEMENT (sigkill) ===
    - event: ptrace
      actions:
        - sigkill
    - event: setuid
      actions:
        - sigkill
    - event: setgid
      actions:
        - sigkill
    - event: init_module
      actions:
        - sigkill
    - event: finit_module
      actions:
        - sigkill
    # === MONITORING (log only) ===
    - event: security_file_open
    - event: sched_process_exec
    - event: net_packet_ipv4
