apiVersion: tracee.aquasecurity.github.io/v1beta1
kind: Policy
metadata:
  name: openclaw-security
  annotations:
    description: Runtime security policy for OpenClaw containers
spec:
  scope:
    - global
  rules:
    - event: ptrace
    - event: security_file_open
    - event: sched_process_exec
    - event: setuid
    - event: setgid
    - event: init_module
    - event: finit_module
    - event: net_packet_ipv4
